const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..','dist');
const speed=JSON.parse(fs.readFileSync(path.join(ROOT,'speed-listening-data.json'),'utf8'));
const core=JSON.parse(fs.readFileSync(path.join(ROOT,'listening-data.json'),'utf8'));
const app=fs.readFileSync(path.join(ROOT,'app.js'),'utf8');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');
const css=fs.readFileSync(path.join(ROOT,'v19-upgrade.css'),'utf8');
const youtubeId=url=>String(url||'').match(/[?&]v=([A-Za-z0-9_-]{6,})/)?.[1]||'';
assert.equal(speed.days,30);
assert.equal(speed.lessons.length,30);
assert.deepEqual(speed.lessons.map(x=>x.day),Array.from({length:30},(_,i)=>i+1));
assert.equal(speed.lessons.filter(x=>x.channel==='TED').length,15);
assert.equal(speed.lessons.filter(x=>String(x.channel).startsWith('Kurzgesagt')).length,15);
assert.equal(new Set(speed.lessons.map(x=>x.id)).size,30);
assert.equal(new Set(speed.lessons.map(x=>youtubeId(x.youtubeUrl))).size,30);
const coreIds=new Set(core.lessons.map(x=>youtubeId(x.youtubeUrl)));
assert.equal(speed.lessons.filter(x=>coreIds.has(youtubeId(x.youtubeUrl))).length,0,'Speed videos must not overlap core listening');
assert.match(html,/UPGRADE SKILLS/);
assert.match(html,/Reading Upgrade/);
assert.match(html,/Listening Upgrade/);
assert.match(html,/Writing Upgrade/);
assert.match(html,/MOCKS/);
assert.match(html,/Reading Mock/);
assert.match(html,/Listening Mock/);
assert.match(app,/Speed Listening 30/);
assert.match(app,/15 ta Gap Filling/);
assert.match(app,/15 ta full-sentence Dictation/);
assert.match(app,/1\.25× \/ 1\.5× Speed Max/);
assert.match(app,/data-action="lb-rate"/);
assert.match(app,/data-sl-answer="gap"/);
assert.match(app,/data-sl-answer="dictation"/);
assert.match(app,/lb-yt-audio-host/);
assert.match(css,/\.nav-group-title/);
assert.match(css,/\.lb-track-switch/);
assert.match(css,/\.sl-speed-row/);
assert.match(sw,/speed-listening-data\.json/);
console.log('V20 Speed Listening smoke checks passed: 30 unique videos, 15 TED + 15 Kurzgesagt, no core overlap.');
