"""One hundred user-selected prompts and concrete, fictional practice anchors."""

# title | phrase category | past detail | present detail | future detail
ROWS = """My family|social|My mother helped me prepare for a school presentation and my brother listened to the rehearsal.|We usually talk over dinner and check how one another's day has gone.|I hope we can keep those ordinary conversations even when our schedules change.
My best friend|social|A classmate stayed after a lesson to help me understand a difficult task.|We still exchange honest feedback and laugh about small mistakes.|I want us to make time to meet even if we study in different cities.
My hometown|hometown|I used to recognise almost every shop on the walk to school in Namangan.|The city feels familiar, but new cafés and bus routes keep appearing.|I would like to see more green public spaces without losing its local character.
My favorite food|food|My family made plov for a small celebration when I was younger.|I enjoy a home-cooked bowl of plov most when we eat together.|I hope to learn the family recipe well enough to cook it for guests.
My daily routine|time|I once tried to plan every hour and became frustrated when a lesson ran late.|Now I keep a short list of priorities and leave room for a walk.|I want a routine that supports study and rest without becoming rigid.
My job|business|I helped with a small school project that felt like a first taste of real responsibility.|At present I am a student, so my main work is learning and completing useful projects.|I hope to build websites that solve practical problems for people.
My favorite hobby|art|I started drawing simple layouts in a notebook after seeing an interesting website.|I now enjoy making small web pages and testing how people use them.|I would like to turn that interest into a longer creative project.
My favorite book|books|A novel from the school library made me stay up to finish one chapter.|I prefer books with believable characters and clear language.|I plan to reread a favorite and notice details I missed before.
My favorite movie|film|I watched an animated adventure with my younger brother on a rainy afternoon.|I still prefer films that give their characters time to grow.|I would like to watch a new film with him and compare our reactions.
My favorite TV show|media|A science programme once explained an everyday question with a simple experiment.|I enjoy short episodes that teach me one clear idea.|I hope to follow a series that explores technology in a thoughtful way.
My weekend plans|planning|One weekend we abandoned an elaborate plan and enjoyed a picnic nearby.|I usually set aside time for family, study and an unhurried walk.|Next weekend I want to visit a quiet park and catch up on reading.
My last vacation|travel|My last short break included a slow visit to Samarkand with relatives.|I still remember its streets more clearly than a list of attractions.|For my next break I would like to explore a smaller town at my own pace.
My future goals|study|I once felt unsure whether to focus on English or coding first.|I now practise both in smaller, manageable sessions.|I hope to study technology abroad and build something useful with the skills.
My favorite sport|sport|A friendly football match taught me to pass instead of trying to do everything myself.|I enjoy football because teamwork changes the whole game.|I would like to keep playing casually with friends as life gets busier.
My morning routine|time|I used to reach for my phone immediately and lose track of time.|These days I get ready, eat breakfast and review my first task.|I want to protect the first quiet half-hour for reading and planning.
My evening routine|sleep|I once stayed up late trying to finish every minor task.|I now put my notes away and spend a little time talking with family.|I hope to make my evenings calmer when my schedule becomes more demanding.
My favorite place to visit|travel|A visit to a small riverside path felt like a welcome break after exams.|I return when I want fresh air and a different view.|I would like to take a friend there and explore the area more slowly.
My favorite music|music|A calm instrumental track helped me concentrate during a busy school week.|I listen to gentle music while organising notes, but prefer silence for difficult reading.|I hope to discover more music from different cultures.
My favorite singer/band|music|I first heard a singer's live performance through a friend's recommendation.|I admire artists who sound sincere rather than relying on a dramatic production.|I would like to hear a small live performance someday.
My favorite holiday|social|A family holiday felt special because everyone helped prepare the meal.|I value the conversations and visits more than elaborate decorations.|I hope to keep that sense of togetherness as our family grows.
My school/university life|study|My first weeks at college felt unfamiliar until I learned the timetable.|I enjoy lessons most when I can test an idea with classmates.|I hope to use future classes to build real projects, not only pass exams.
My childhood memories|memory|I remember making a little town from building blocks on the floor.|Old photos sometimes bring back the sounds and conversations around that afternoon.|I hope to record a few family stories before their details fade.
My favorite teacher|study|One teacher explained a difficult rule with a simple real-life example.|I still remember how patiently she listened to questions.|I want to learn from teachers who give honest, useful feedback.
My pet (or pet I’d like to have)|animals|I enjoyed looking after a relative's friendly cat for a short time.|I do not keep a pet now, so I think carefully about the responsibility involved.|I might adopt a pet later when I can offer the time and care it needs.
My favorite season|nature|A cool autumn walk after school made me notice the changing leaves.|I like autumn's gentle weather and quieter streets.|I hope to take more short trips in autumn rather than stay indoors.
My favorite weather|nature|After a hot week, a mild rainy day made the air feel fresh.|I prefer cool, clear weather for walking and studying.|I would plan an outdoor day when the forecast looks comfortable.
My favorite festival|social|A local cultural event brought neighbours together through music and food.|I enjoy festivals where visitors can actually talk and take part.|I would like to learn the story behind another region's celebration.
My first job|business|My first responsibility was helping organise a school event rather than a paid position.|I am currently focused on studying and building small skills.|I hope my first paid role will let me learn from patient colleagues.
My favorite subject in school|study|I liked an English lesson that made us explain our own ideas aloud.|English remains useful because it opens access to books and people.|I hope to combine language skills with technology in future study.
My favorite restaurant|food|A small family restaurant impressed me with a simple meal and friendly service.|I choose calm places where conversation is easy.|I would like to return with my family and try something new from the menu.
My favorite dessert|food|My sister once made a simple homemade cake for a birthday.|I enjoy a small slice when the family shares a special occasion.|I would like to learn to make that recipe myself.
My favorite clothing style|clothes|I once bought an item because it looked trendy but hardly wore it.|I prefer simple, practical clothes that suit my daily routine.|I plan to choose fewer, more useful items when shopping.
My favorite technology|tech|Using an older laptop showed me how frustrating slow software can be.|I value a reliable computer that helps me study and create.|I would like to try tools that make accessible learning easier.
My dream house|home|A relative's bright house near a park gave me the idea.|I imagine a quiet desk by a window and space for family conversations.|I hope to live somewhere comfortable with good light and easy access to nature.
My favorite app|tech|A simple notes app helped me keep track of a school project.|I use apps that solve one clear problem without constant notifications.|I would like to design an app that makes language practice easier.
My role model|social|My mother's patience during a difficult school task made an impression on me.|I admire how she listens before offering advice.|I hope to show the same steadiness when someone asks for my help.
My best birthday|social|One birthday at home stands out because my family shared old stories over cake.|I now value a relaxed celebration more than a large party.|I would like to spend a future birthday on a simple day out together.
My favorite sport to play|sport|I joined a school football match even though I was nervous at first.|I play football for the teamwork and the chance to move around.|I hope to keep it as an enjoyable activity with friends.
My favorite athlete|sport|An interview with an Uzbek athlete introduced me to her training routine.|I admire the patience behind consistent improvement.|I would like to hear how she handles a setback and returns to practice.
My ideal weekend|time|A quiet weekend with a picnic and no strict schedule felt unusually refreshing.|I try to balance a useful study session with time outside.|I would plan a short day trip without filling every hour.
My travel bucket list|travel|Seeing photos of historic streets made me curious about Samarkand.|I keep a short list of places I would genuinely like to explore.|I hope to visit a new country slowly enough to understand daily life there.
My favorite memory|memory|I remember finishing a class project with friends after several false starts.|The shared relief still makes me smile when I see the old photo.|I hope to make more memories through meaningful projects and trips.
My morning commute|driving|A delayed bus once taught me to leave home with extra time.|I usually notice familiar shops and the changing light on the way to class.|I hope future transport is reliable enough to make commuting less stressful.
My favorite childhood game|children|I used to build imaginary streets with coloured blocks on the floor.|I still appreciate games that let players invent their own solutions.|I would like to teach a younger relative the game one day.
My favorite social media platform|media|A useful lesson online first showed me that a short video could teach a skill.|I follow creators who explain ideas clearly and check sources.|I hope platforms make it easier to find thoughtful content.
My workout routine|health|I used to try an unrealistic schedule and then stop when school became busy.|I now choose moderate movement that fits my day and leaves room for rest.|I want to keep an enjoyable, flexible routine as my responsibilities change.
My favorite outdoor activity|nature|A long walk with a friend helped us talk after a busy week.|I enjoy walking in a park where I can notice the trees and people.|I would like to try more gentle hikes with enough time to enjoy the view.
My favorite indoor activity|books|Reading in a quiet room helped me focus during a rainy weekend.|I enjoy a good book when I want a break from screens.|I hope to make a small reading corner in a future home.
My favorite quote|books|A teacher once shared a short line about learning from mistakes.|I remember the idea rather than repeating the exact words.|I hope to use that principle when a future plan needs changing.
My favorite historical figure|study|A school lesson introduced me to a scholar who pursued knowledge across fields.|I admire curiosity combined with a willingness to explain ideas clearly.|I would like to read a thoughtful biography rather than rely on brief summaries.
My dream job|business|A small website project showed me the pleasure of solving a real problem.|I am learning the foundations of web development one project at a time.|I hope to build accessible learning tools with a supportive team.
My favorite time of day|time|I used to like late evenings because the house became quiet.|I now appreciate early morning light before the day gets busy.|I hope to protect a calm hour for focused work wherever I live.
My favorite color|art|I chose deep blue for a school poster and liked how clearly the text stood out.|I still prefer blue because it feels calm and works with many designs.|I would use it as one accent in a future room rather than everywhere.
My favorite animal|animals|A gentle cat at a relative's house patiently watched us from the garden.|I like cats for their curious, independent behaviour.|I might care for one later if I can provide a stable home.
My favorite museum|art|A local history display helped me imagine ordinary life in another period.|I prefer exhibits with clear explanations and objects you can examine closely.|I would like to visit a science museum with hands-on demonstrations.
My favorite beach|nature|I once spent an afternoon beside a quiet stretch of water with my family.|I prefer calm shores where there is room to walk and talk.|I hope to visit a coastal town and explore beyond the crowded waterfront.
My favorite city|city|A trip to Samarkand made its streets and old square memorable to me.|I appreciate cities that combine useful services with walkable areas.|I would like to return and explore a different neighbourhood slowly.
My favorite country|travel|Pictures and stories about South Korea first caught my attention.|I am interested in its language, technology and everyday culture.|I hope to study there and learn what life is like beyond tourist attractions.
My favorite TV character|film|A thoughtful character in a family series surprised me by admitting a mistake.|I prefer characters who change through their choices.|I would like to watch more stories with believable growth rather than simple heroes.
My favorite superhero|film|I liked a hero who solved a problem by working with friends.|I enjoy stories where responsibility matters as much as special abilities.|I would like to see a film that explores what the hero learns after making a mistake.
My favorite villain|film|A fictional antagonist once made a story interesting because the motives were understandable.|I find complex characters more engaging than one-dimensional ones.|I would enjoy a future story that explores consequences without excusing harmful choices.
My favorite comedian|media|A performer made our family laugh with a gentle observation about daily life.|I enjoy humour that notices ordinary situations without mocking people.|I would like to see a live set with the same thoughtful style.
My favorite author|books|A novel introduced me to an author who wrote believable conversations.|I enjoy writers who trust readers to notice small details.|I hope to read more of that author's work in the original language.
My favorite poet|books|A short poem discussed in class made a familiar place sound new.|I like poetry with a clear image and room for interpretation.|I would like to explore poems from another language alongside good translations.
My favorite painting|art|A landscape at a small exhibition drew my attention to its changing light.|I still remember the quiet colours more than the artist's name.|I hope to see it again and notice something different.
My favorite sculpture|art|A simple public sculpture made me walk around it to understand its shape.|I like works that change as you view them from different angles.|I would like to visit a sculpture garden and compare the works outdoors.
My favorite car|driving|A practical family car made a long trip surprisingly comfortable.|I value reliability, clear visibility and enough room over showy details.|I would choose an efficient car only if it truly suited my needs.
My favorite gadget|tech|A small portable charger once kept my device working during a long study day.|I prefer gadgets that solve a practical problem without taking over my attention.|I would like a lightweight device that helps me organise ideas on the move.
My favorite game|children|A cooperative puzzle game kept my friends talking long after we finished.|I enjoy games that reward planning and clear communication.|I would try a new cooperative game with friends on a quiet weekend.
My favorite board game|children|A family board game taught me to explain rules patiently to younger players.|I like games where everyone stays involved until the end.|I would bring one to a future family gathering.
My favorite card game|children|A simple matching card game made a rainy afternoon enjoyable with cousins.|I like the conversation around the table more than keeping score.|I would teach it to younger relatives as a relaxed group activity.
My favorite holiday destination|travel|A short visit to a quiet town showed me how restorative a small trip can be.|I prefer places with local streets to explore at an easy pace.|I would spend a few days near the mountains and take unhurried walks.
My favorite ice cream flavor|food|I chose vanilla on a family outing and liked its simple taste.|I still enjoy vanilla, especially on a warm day with friends.|I would try a new fruit flavour next time while keeping vanilla as a safe choice.
My favorite drink|food|My mother made warm tea for us after a cold walk.|I usually prefer water or tea, depending on the weather.|I would like to learn how different cultures prepare tea.
My favorite sandwich|food|A homemade sandwich saved time on a school trip.|I prefer fresh bread, vegetables and a filling that is easy to carry.|I would make a picnic version with my own combination of flavours.
My favorite salad|food|A simple tomato and cucumber salad accompanied a memorable family meal.|I like fresh ingredients and a light dressing.|I would try adding herbs from a small home garden.
My favorite souvenir|memory|A postcard from a short trip reminded me of a conversation more than the attraction itself.|I keep small souvenirs when they are connected to a clear story.|I would rather bring home one meaningful item than a bag of similar objects.
My favorite childhood toy|children|Building blocks let me invent a little town and rebuild it when it fell over.|I still remember how much freedom that simple toy gave me.|I would pass on a similar set to a younger child and let them create their own designs.
My favorite scent|memory|The smell of fresh bread used to tell me breakfast was ready.|I like familiar, gentle scents that remind me of ordinary family moments.|I hope a future home has the same welcoming feeling without relying on anything elaborate.
My favorite flower|nature|A small patch of spring flowers brightened a neighbour's garden.|I like simple flowers that grow well in local conditions.|I would plant a few near a window or in a small garden.
My favorite tree|nature|A large shade tree near our walking route gave us a place to pause.|I appreciate trees that make a street more comfortable in summer.|I hope new neighbourhoods leave room for mature trees.
My favorite park|nature|A local park was the setting for a low-cost picnic with friends.|I enjoy its paths and the chance to walk without rushing.|I would like to see better seating and more accessible paths there.
My favorite garden|nature|My aunt showed me the herbs she grew in a small corner of her garden.|I like how she makes limited space feel lively and useful.|I would try growing a few easy plants and learn by watching them change.
My favorite mountain|nature|Seeing distant mountains on a car trip made the view feel wider.|I enjoy looking at mountain scenery from safe walking paths.|I would like to visit a mountain town and take a guided, gentle walk.
My favorite river|nature|The first time I saw part of the Syr Darya, a school map felt real.|I think of rivers as part of the communities around them.|I hope to learn more about how local people protect the water.
My favorite lake|nature|A quiet lakeside stop on a trip gave us time to sit and talk.|I prefer calm water and paths where visitors can walk respectfully.|I would like to revisit a lake with friends and take time to observe the surroundings.
My favorite forest|nature|A tree-lined area on a countryside visit felt cooler and quieter than the road.|I enjoy the layered sounds and filtered light in wooded places.|I would like to explore a marked forest trail with someone who knows the area.
My favorite movie genre|film|An animated adventure made me realise a film can be imaginative and thoughtful.|I prefer stories with humour, believable characters and a clear emotional arc.|I would try a documentary film as well to broaden what I watch.
My favorite book genre|books|A fantasy novel first made me eager to finish a long book.|I like imaginative stories that still explore recognisable choices.|I would read more historical fiction to compare a different kind of setting.
My favorite magazine|books|A science magazine in the library introduced me to a surprising question.|I read short features when they explain ideas with reliable examples.|I would subscribe to a digital edition if it helped me learn regularly.
My favorite newspaper|media|A local report once explained a change to our bus route.|I prefer clear reporting that separates facts from opinion.|I would follow a publication that corrects errors openly and covers my region.
My favorite podcast|media|An English podcast helped me hear different accents during a commute.|I listen to episodes with useful stories rather than long introductions.|I would like to follow a series about everyday science and language.
My favorite YouTube channel|media|A teacher's short grammar explanation helped me solve a practice question.|I follow channels that show examples and explain their reasoning.|I hope to find more creators who update lessons when information changes.
My favorite lecture|study|A guest speaker used one personal story to explain a broad idea.|I remember lectures that leave time for honest questions.|I would like to attend a talk on designing useful technology.
My favorite class|study|A practical English class made everyone explain an idea in their own words.|I enjoy classes where feedback leads to a second attempt.|I would choose more project-based classes in future study.
My favorite school project|study|Our group made a poster with a hand-drawn map when materials were limited.|I learned that a clear plan mattered more than complicated decoration.|I would like to build a digital version with better accessibility.
My favorite art project|art|I designed a simple poster and changed the layout after classmates tested it.|I enjoy projects where feedback visibly improves the result.|I would try a small illustrated story with a clear visual sequence.
My favorite science experiment|study|We predicted the result of a simple water demonstration before testing it.|I like experiments that make an abstract idea visible.|I would repeat a safe classroom experiment and explain the outcome to younger students.
My favorite DIY project|art|I once made a desk organiser from spare cardboard for my notebooks.|I still like small projects that solve a real problem at home.|I would design a sturdier version and ask someone else to test it.
My day|time|One particularly busy day before a presentation taught me to choose priorities.|Today I balance lessons, a focused English session and time with family.|Tomorrow I want to start with the hardest task and leave the evening less crowded."""

TOPICS = [line.split("|") for line in ROWS.splitlines()]
assert len(TOPICS) == 100 and all(len(row) == 5 for row in TOPICS)
